language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

matrix:
  include:
    - python: '3.6'
      env: TOXENV=linting

install:
  - pip install tox-travis coveralls

script:
  - tox

after_success:
  - coveralls

deploy:
  provider: pypi
  user: nicoddemus
  skip_upload_docs: true
  password:
    secure: bB4adUZVIkt31cmNklskyIDNehujKToGnStnlunp7P8CBF6CGeNqkYU17emAPvfZbTb/ClUpiO9r6AD1ej32Uyr+I8qUyhuYtHG3JGp+WRR/tw+ytAZIJ9i+PMjBv1RAdyLENJ/Tx0LKHKsABr8dQIieLFqKZJuT77f/5ZkvI/U=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: pytest-dev/pytest-mock
    condition: $TRAVIS_PYTHON_VERSION = 3.5
