language: python
python: 2.7
env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py32
  - TOX_ENV=py33
  - TOX_ENV=pypy

install:
  - pip install tox coveralls --use-wheel

script:
  - coverage run --source=pytest_mock.py runtox.py -e $TOX_ENV

after_success:
  - coveralls
